### ISSUE TITLE
Coding style: Using early returns for control flow

### ISSUE THREAD

**Issue by boennemann** [upfrontIO/guides#19]
I used this pattern here: https://github.com/upfrontIO/livingdocs-framework/blob/feat-undo-redo-event/src/history/events/moved-removed.coffee#L1-L16

```coffee
exports.revert = (livingdoc, model, context) ->
  previous = livingdoc.componentTree.findById(context.previous)
  next = livingdoc.componentTree.findById(context.next)
  container = context.parentContainer || livingdoc.componentTree.root

  unless previous || next
    # neither previous nor next
    # appending at the end to not lose data
    container.append(model)
    return

  unless previous
    container.insertBefore(next, model)
    return

  container.insertAfter(previous, model)
```

@masone: 

> I'm unsure about these conditionals with early returns. It's clean, but still feels a bit weird. I have never used early returns in that way, but more for scenarios like return unless foo.
> in essence, this is a if, else if, else scenario, which would be easier to read. But then the first conditional would be harder to read.
> Just jotting my thoughts down... No action required unless you agree.

@peyerluk:

> This will work better I think:
```coffee
if previous
  ...
else if next
  ....
else
  ...
return true
```

**Comment by boennemann** [comment]
I'm deliberately avoiding if/else for control flow and I'm always preferring early returns.

First: What is it that I'm trying to achieve with this style?
I'm always trying to eliminate edge cases that the reader of this code would have to track mentally.
By checking the conditions for edge cases, or a cases that you'd not assume "normal", first, they're out of the way as soon as possible. By returning instead of resorting to else constructs it's immediately obvious that this code path is over. This requires way less context, because in an if/elseif/else cases as described above I'd have to consider 3 possible outcomes at the same time.

Writing the code the way I did it's clear what I expect to usually happen and given the input the output is immediately predictable.

Another side effect of this is, that it avoids unnecessary indents – the enemy of all readability.
The "main" case will always be written without indentation at all. Edge cases/Errors can usually be handled with very few LOC, while the main logic can remain unindented and easy to read.

**Comment by masone** [comment]
I get the benefits of early returns. But here, two people are pointing out that this is unreadable. Of course you can ignore the advice, but I'd recommend to think about trading your personal preferences for readability.

**Comment by marcbachmann** [comment]
I think it completely depends on the code you're working on.
In general, we use them everywhere in our code base and I think it will stay like that.

**Comment by marcbachmann** [comment]
I would also suggest a rewrite here, but it's not releated to the early returns at all.
Just because you can get rid of those two return calls. And you can add an explicit return at the button.
I suppose that's what @peyerluk wanted to suggest.

**Comment by boennemann** [comment]
>  trading your personal preferences for readability

Sorry to pick on individual words, but this is a paradox. Readability is subjective, which is why people have preferences. Something I can get behind is **trading personal preferences for the team's agreed upon preferences**. This is exactly what I'm a huge fan of and why I have opened this issues in this location.

The original feedback I received on this is subjective, which is why I moved it out of the original PR and into our style guide repo. This is a question of yet undefined coding style, so now there would have been the opportunity to balance upsides and downsides and to define what the team's future preference is.

I tried to make a start by listing (as objectively as I could) upsides of my personal preferences to make a strong point, obviously in the hopes that it'll end up as the team's preference.

Even though I'm not convinced that if/elseif/else improves readability in this case, because I haven't heard any points that would support that, I'm now accepting this as my new coding style inside livingdocs code, because I'm outgunned in numbers. This is totally fine for me, as it is a very important part of this process. Of course I would have loved to hear some points, so I have a better feeling while doing so, but as a teamplayer and professional I can do without.

What I don't like is the sentiment that I'm incapable of accepting advise or sticking to existing rules, while navigating entirely inside of what is currently defined. I see that my language ("I'm deliberately avoiding if/else for control flow and I'm always preferring early returns.") was a tad too forceful. I was referring to how I would do things if they're fully in my control, and not that I'm ignoring your advice. I'll frame that in a more hypothetical way next time.

I would love to get to a point where it's possible to raise such a discussion without running against killer arguments like "that's not readable", or "it's like this, and that's why it will stay like this". I totally understand that a lot of this is very subjective and it's not always easy to express why there are certain preferences, or that there are economical reasons to reject certain ideas. That doesn't mean that it can't be written down and explained like this. 
If we can't reach such a discussion culture, we're incapable of ever changing things. Things will continue to change around us though.

**Comment by peyerluk** [comment]
> I would love to get to a point where it's possible to raise such a discussion without running against killer arguments like "that's not readable"

You are right that "that's not readable" is a tough argument to deal with. But often it just means "I had a hard time understanding this piece of code" which in turn is very valuable. When we are immersed in writing a feature we have packed a lot of stuff and assumptions in our working memory and it is very hard to guess how well a new coder will understand a certain piece of code. And everyone who struggles with our code provides valuable feedback even if they cannot pinpoint why they have a hard time understanding it. Think about this as measuring the bounce rate on a website. If it is high we as authors should ask ourselves why that is. I don't think we have to change something immediately every time someone brings up the 'hard to read' argument. But it is valuable feedback even without a detailed reasoning behind it.

In the example above I can explain why it was hard for me in particular. I have a mental model of the insertion process where there are three different options that are of equal importance (append, insertAfter and insertBefore). In my mind there is no 'normal' case and some 'edge' case thus the `if`, `else`and `else if` fits this model much easier. This is subjective and I understand that other people can have different mental models. If someone gets confused about code that seemed obvious to me I normally ask myself why that could be and what could be done to clarify things.

In the above example both me and @masone gave you feedback about how we felt when reading this particular method. It was never about early returns or adhering to a styleguide. We just let you know that we stumbled when reading this. That's all. It's not meant to criticise you as we all understand that it is very hard to write code that everyone understands. I still fail at this way more than I feel comfortable with. I think encouraging people to give feedback is one of the best ways to get better. But sometimes that means just take feedback as feedback and not forcing others to justify what they said. And you in turn do not have to justify every line of code if someone does not agree with you. I would suggest to give it some time. Normally the different views enrich each other after a few months. It just takes some time and consideration.

**Comment by masone** [comment]
Wow this debate is getting hotter than it needs to be :fire: 
Sorry If I stepped on your toes, that was not my intention. I should have taken more time and give better feedback.

Lukas' explanation is exactly how I'm feeling and I think we're all on the same page. 

- Feedback and reviews are always subjective
- You can always choose to ignore it
- You're very welcome to educate on better coding practices. Maybe this was just the wrong piece of code to discuss your point
- There was a misunderstanding about the feedback. It happens - don't give up so quickly
