### ISSUE TITLE
RequireJS vs Browserify

### ISSUE THREAD

**Issue by peyerluk** [upfrontIO/guides#6]
Or put differently: AMD vs CommonJS

Philipe has already done a spike solution for requireJS with the livingdocs-engine: [RequireJS-Setup](/upfrontIO/requirejs-setup)

Here are some goals that we should try to accomplish:
- Loading of livingdocs-engine and EditableJS into the livingdocs-editor and other projects
- Sharing of code between the browser and NodeJS (most importantly the livingdocs-engine)
- Reducing the problem of load order of scripts
- Improving testability of our code
- Making modularization of our code easier
- Compatibility and ease of use with AngularJS

**Comment by boennemann** [comment]
And the winner is: CommonJS
